### PR TITLE
feat: kustomize deployment

### PR DESCRIPTION
**Pull request by skymoore**
add kustomize kubernetes deployment

https://github.com/saleor/saleor-platform/pull/208
https://github.com/saleor/saleor/pull/11250
https://github.com/saleor/react-storefront/pull/631
https://github.com/saleor/saleor-dashboard/pull/2624

### CODE REVIEW

**Comment by lkostrowski** [comment]
Hey @skymoore , thanks for your contribution.

We'd like to support the community with deployment guides, but we are not sure if we want to merge them into the Saleor codebase. 

Accepting the PR means that Saleor will take ownership of maintaining these guides, which we can't guarantee. We can't possibly have the knowledge about all of these platforms to keep IaaC up to date.

However, we all agree that you should take credit for your work. If you create your own repository/readme/example, we will be super happy to link to it from our docs and other resources

**Comment by skymoore** [comment]
@lkostrowski  Hi, thank you for the reply.  My deployment is on the slr.rwx.dev branch of my saleor-platform fork: [here](https://github.com/skymoore/saleor-platform/tree/slr.rwx.dev).  The kustomization is in /deployment/kubernetes/environments/slr.rwx.dev.  I think though for the purpose of an example and easy understanding, I'll create a repo with just the kustomize manifests.

I didn't see an examples or example deployments section in the docs.  Suppose I should make a PR to the [saleor-docs](https://github.com/saleor/saleor-docs) and add that section?

**Comment by lkostrowski** [comment]
@skymoore if you create a separate repo, it will be for sure better, easier to search and find.

Indeed we don't have examples in docs, only few dedicated pages [here](https://docs.saleor.io/docs/3.x/developer/running-saleor/docker)

I think we need to create some introduction document, pointing to community resources, including your contribution. Let us handle the docs :) cc @peelar

**Comment by skymoore** [comment]
@lkostrowski @peelar [kustomize deployment repo](https://github.com/skymoore/saleor-platform-k8s-kustomize)  I'll keep adding to this, and improve the readme.

**Comment by skymoore** [comment]
@lkostrowski also if you could help with [this issue](https://github.com/saleor/saleor/issues/11267) i would really appreciate it.

**Comment by lkostrowski** [comment]
@skymoore fyi https://github.com/saleor/saleor-docs/issues/597

**Comment by skymoore** [comment]
@lkostrowski  Appreciate you!

**Pull request closed without merging**
