### PR TITLE
Remove Mailhog in favor of Mailpit

### PR DESCRIPTION
**Pull request by carlosa54**
This PR removes Mailhog in favor of Mailpit. See https://github.com/saleor/saleor/pull/12447 for context

### CODE REVIEW

**Review by maarcingebala — APPROVED** [review]

**Review by IKarbowiak — APPROVED** [review]

**Comment by magul** [comment]
Hi @carlosa54 , thank you for you're contribution!

As your change in Saleor core will be part of Saleor 3.13 and `saleor-platform` follow released images of Saleor core, we will merge this pull request alongside introduction of 3.13 into platform.

**Review by NyanKiyoshi — CHANGES_REQUESTED** [review]
I do not see `EMAIL_URL` being set to point to mailpit which makes me believe this PR doesn't work (and thus mailhog wasn't working).

I do not have time to verify it works. Can someone confirm that it works or doesn't work?

**Comment by carlosa54** [comment]
@NyanKiyoshi saleor-platform is not currently including any `EMAIL_URL` variable in the repo. There's a mention of mailhog in the [saleor docs](https://docs.saleor.io/docs/3.x/developer/running-saleor/debugging-emails) that can be updated.

This does work in the same way that Mailhog was currently setup in saleor-platform

**Comment by maarcingebala** [comment]
@NyanKiyoshi Please open an issue about it; we can fix it separately.

**Pull request merged**
